### ISSUE TITLE
X.509 module available

### ISSUE THREAD

**Issue by waja** [bodsch/docker-icingaweb2#26]
It would be totally awesome to have https://github.com/icinga/icingaweb2-module-x509 included. :)

**Comment by bodsch** [comment]
i can hear you! :)
try the coming release.

**Comment by waja** [comment]
is this really fixed?

**Comment by bodsch** [comment]
i think so.
you can insert 'things' in the web interface and the backgroundprocesses pink them up and do 'things'.
the limitations are aktually the module limitations.
like missing validator for the cron job

**Comment by bodsch** [comment]
any tests or feedback?
