### ISSUE TITLE
Editing Proxys to Icingaweb2

### ISSUE THREAD

**Issue by Bltzz** [bodsch/docker-icingaweb2#28]
You have to set an Environment var (ENV http_proxy=http://myproxy.test; https_proxy=http://myproxy.test) 
in Dockerfile in every section. In the first section you have to add the command "RUN \ pear config-set http_proxy $(printenv http_proxy)" before the pecl channel update line. 
In addition to this you need to set an no_proxy=icinga2-master in the seccond section and the docker-compose.yml in the icingaweb2 environment.

**Comment by bodsch** [comment]
i use this way:
```
$ cat ~/.docker/config.json 
{
  "proxies": {
    "default": {
      "httpProxy": "http://172.17.0.1:3128",
      "httpsProxy": "http://172.17.0.1:3128",
      "noProxy": "localhost,127.0.0.1,.*.monitoring.lan"
    }
  }
}
```
The container can then be built without any problems.

The corresponding environment variables are removed after the container is started: 
https://github.com/bodsch/docker-icingaweb2/blob/master/rootfs/init/run.sh#L42-L45

Please test the current master branch, or the latest container from docker-hub!

**Comment by bodsch** [comment]
@Bltzz any questions?
