### ISSUE TITLE
How can I make this work on Kubernetes?

### ISSUE THREAD

**Issue by yfried** [bodsch/docker-icingaweb2#36]
Hi, I have my own icinga-docker and I'm trying to make it work with this image on a Kubernetes cluster.
This works using docker-compose, but fails on the k8s cluster ( all containers are in a single pod, communicating via localhost).

I'm seeing the following error on the master: `critical/ApiListener: Client TLS handshake failed (from [127.0.0.1]:48504): Error: Socket was closed during TLS handshake.`

I'd appreciate  any help you can provide.

**Comment by bodsch** [comment]
If you provide me with a Kubernetes cluster and your configuration, I will be happy to look at it.

**Comment by yfried** [comment]
Never mind. I managed to do this on my own with a few minor modifications. tnx.
I think the error is actually the first time the icingaweb docker tries to access the icinga-master docker. That's ok and can be ignored. the actual connection comes long after that.

**Comment by bodsch** [comment]
can you still send me your configuration?
i might extend my tests to Kubernetes, although i don't see any sense in it.
