### ISSUE TITLE
No notifications are sent

### ISSUE THREAD

**Issue by svenihoney** [bodsch/docker-icingaweb2#6]
I am unable to generate notifications at all using the combination of the icinga2/icingaweb2 images. If I import the director configuration into another docker-based icingaweb2/director image, notifications are generated correctly.

Do you have an idea where I could look after?

Regards,
Sven

**Comment by svenihoney** [comment]
In base icinga2 image, notification feature is disabled... :-(

**Comment by bodsch** [comment]
you can add a payload into rootfs/opt/startup.sh or create an PR to enable notifications. :)
